version: 2

models:
  - name: customer_details
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
  - name: stg_customer
    columns:
      - name: customer_id
        tests:
          - unique
          - not null
      - name: salary_employee
        tests:
          
